# PyTorch Introduction
## PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
### Can be seen as substitute of NumPy with GPU capabilities
A Tensor is just a more generic term than matrix or vector.
PyTorch Tensors There appear to be 4 major types of tensors in PyTorch: Byte, Float, Double, and Long tensors. Each tensor type corresponds to the type of number (and more importantly the size/preision of the number) contained in each place of the matrix.


## NumPy:
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
* For Numpy docs: Refer the following https://docs.scipy.org/doc/numpy-1.13.0/reference/

In [1]:
import torch

## A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
A very similar package for `numpy.ndarray`. It basically supports almost every major computation of numpy

### Lets dive in and see some basic pythonic operations

In [2]:
x = torch.zeros(2,3)
x

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [3]:
x = torch.ones(2,3)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [4]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x


tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000])

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x


RuntimeError: Overflow when unpacking long

## Convert NumPy to PyTorch and vice-versa
With almost no computation cost, you can convert PyTorch tensor to NumPy array and any change in the converted NumPy array will reflect on the original PyTorch tensor

In [8]:
import numpy as np

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)

x2

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])

In [9]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

# Defining a numpy array and converting it to a Torch tensor
# a = np.ndarray(shape=(2,3), dtype=float)
# a = torch.from_numpy(a)
# a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [11]:
# x_gpu = x.cuda()
# x_gpu

In [12]:
# tensor.size() -> indexing also possible

x = torch.FloatTensor(10,12,3,3)

x.size()[:]

# x.size()[:2]
# x.size()

torch.Size([10, 12, 3, 3])

## The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [13]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

x,out


(tensor([[ 0.3563,  0.2490,  0.9389],
         [ 0.4853,  0.4226,  0.0435],
         [ 0.6219,  0.6776,  0.9109],
         [ 0.7957,  0.6474,  0.6615]]), tensor([[ 0.3563,  0.2490,  0.9389],
         [ 0.7957,  0.6474,  0.6615]]))

### Pythonic Indexing

In [14]:
# pythonic indexing also works

x[:,0],x[0,:],x[0:2,0:2]

# name = 'abhishek'
# name = name[0:2]
# name

(tensor([ 0.3563,  0.4853,  0.6219,  0.7957]),
 tensor([ 0.3563,  0.2490,  0.9389]),
 tensor([[ 0.3563,  0.2490],
         [ 0.4853,  0.4226]]))

### Torch masking

In [15]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

(tensor([[ 0.3981, -0.3454,  1.0125],
         [ 0.1035, -0.7925, -0.0559]]), tensor([[ 0,  0,  1],
         [ 0,  1,  0]], dtype=torch.uint8), tensor([ 1.0125, -0.7925]))

In [16]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2


(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

## Math Functions

### Torch provides MATLAB-like functions for manipulating Tensor objects. 

`torch.add(tensor, value)`
Add the given value to all elements in the `Tensor`.


`y = torch.add(x, value)` returns a new `Tensor`.

`x:add(value)` add `value` to all elements in place.

In [17]:
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2


(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]), tensor([[  2.,   4.,   6.],
         [  8.,  10.,  12.]]), tensor([[  2.,   4.,   6.],
         [  8.,  10.,  12.]]), tensor([[ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]))

### Matrix matrix product of `mat1` and `mat2`. 
If mat1 is a n × m matrix, mat2 a m × p matrix, res must be a n × p matrix.

`torch.mm(x, y)` puts the result in a new Tensor.

`torch.mm(M, x, y)` puts the result in M.

`M:mm(x, y)` puts the result in M.

In [18]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[       -inf,        -inf, -1.2222e+02, -9.6046e+07,        -inf],
        [ 0.0000e+00, -7.2378e-25,  0.0000e+00, -7.2378e-25,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [19]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)

x1 = torch.eig(x1,True)
x1

RuntimeError: Overflow when unpacking long

## PyTorch Autograd

In [20]:
from torch.autograd import Variable

### Autograd is now a core torch package for automatic differentiation. It uses a tape based system for automatic differentiation.

In autograd, there is a Variable class, which is a very thin wrapper around a Tensor. 
You can access the raw tensor through the `.data attribute`, and after computing the backward pass, a gradient w.r.t. this variable is accumulated into `.grad attribute`.

#### We wrap our PyTorch Tensors in Variable objects; a Variable represents a node in a computational graph. If x is a Variable then `x.data` is a Tensor, and `x.grad` is another Variable holding the gradient of x with respect to some scalar value.

In [21]:
dtype = torch.FloatTensor
# dtype = torch.cuda.FloatTensor # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

Create random Tensors to hold input and outputs, and wrap them in Variables.
Setting `requires_grad=False` indicates that we do not need to compute gradients with respect to these Variables during the backward pass.


In [22]:
x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)

#### Create random Tensors for weights, and wrap them in Variables.
#### Setting requires_grad=True indicates that we want to compute gradients with respect to these Variables during the backward pass.

In [23]:
w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)

### Forward pass: 
compute predicted y using operations on Variables


### Use autograd:
to compute the backward pass. This call will compute the gradient of loss with respect to all Variables with requires_grad=True.

After this call w1.grad and w2.grad will be Variables holding the gradient of the loss with respect to w1 and w2 respectively.


### Update weights:
using gradient descent; w1.data and w2.data are Tensors, w1.grad and w2.grad are Variables and w1.grad.data and w2.grad.data are Tensors.

#### Manually zero the gradients after running the backward pass

In [24]:
learning_rate = 1e-6
for t in range(500):
  y_pred = x.mm(w1).clamp(min=0).mm(w2)
  
  # Compute and print loss using operations on Variables.
  # Now loss is a Variable of shape (1,) and loss.data is a Tensor of shape
  # (1,); loss.data[0] is a scalar value holding the loss.
  loss = (y_pred - y).pow(2).sum()
  print(t, loss.data[0])


  loss.backward()

  w1.data -= learning_rate * w1.grad.data
  w2.data -= learning_rate * w2.grad.data

  # Manually zero the gradients after running the backward pass
  w1.grad.data.zero_()
  w2.grad.data.zero_()

/Users/pymacbit/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  if __name__ == '__main__':


0 tensor(2.9965e+07)
1 tensor(2.7629e+07)
2 tensor(2.9247e+07)
3 tensor(3.0065e+07)
4 tensor(2.6842e+07)
5 tensor(1.9622e+07)
6 tensor(1.1864e+07)
7 tensor(1.00000e+06 *
       6.3718)
8 tensor(1.00000e+06 *
       3.3793)
9 tensor(1.00000e+06 *
       1.9378)
10 tensor(1.00000e+06 *
       1.2531)
11 tensor(1.00000e+05 *
       9.0562)
12 tensor(1.00000e+05 *
       7.0774)
13 tensor(1.00000e+05 *
       5.7996)
14 tensor(1.00000e+05 *
       4.8841)
15 tensor(1.00000e+05 *
       4.1789)
16 tensor(1.00000e+05 *
       3.6119)
17 tensor(1.00000e+05 *
       3.1445)
18 tensor(1.00000e+05 *
       2.7530)
19 tensor(1.00000e+05 *
       2.4217)
20 tensor(1.00000e+05 *
       2.1390)
21 tensor(1.00000e+05 *
       1.8964)
22 tensor(1.00000e+05 *
       1.6870)
23 tensor(1.00000e+05 *
       1.5052)
24 tensor(1.00000e+05 *
       1.3468)
25 tensor(1.00000e+05 *
       1.2083)
26 tensor(1.00000e+05 *
       1.0866)
27 tensor(97929.0781)
28 tensor(88440.0781)
29 tensor(80031.5781)
30 tensor(

# PyTorch NN module

The nn package defines a set of Modules, which you can think of as a neural network layer that has produces output from input and may have some trainable weights.



In [25]:
N, D_in, H, D_out = 64, 1000, 100, 10

### Create random Tensors to hold inputs and outputs, and wrap them in Variables.


In [26]:
x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

### Use the nn package to define our model as a sequence of layers.
nn.Sequential is a Module which contains other Modules, and applies them in sequence to produce its output. 
Each Linear Module computes output from input using a linear function, and holds internal Variables for its weight and bias.


In [27]:
model = torch.nn.Sequential(
          torch.nn.Linear(D_in, H),
          torch.nn.ReLU(),
          torch.nn.Linear(H, D_out),
        )

### Loss Function:
The nn package also contains definitions of popular loss functions; in this case we will use Mean Squared Error (MSE) as our loss function.
We'll also initialise the learning rate


In [28]:
loss_fn = torch.nn.MSELoss(size_average=False)

learning_rate = 1e-4

## Optimization:
Use the optim package to define an Optimizer that will update the weights of the model for us. 

Here we will use Adam; the optim package contains many otheroptimization algoriths. 
The first argument to the Adam constructor tells the optimizer which Variables it should update.

In [29]:
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

### Forward pass: 
compute predicted y by passing x to the model. Module objects override the __call__ operator so you can call them like functions. 
When doing so you pass a Variable of input data to the Module and it produces a Variable of output data.

### Compute Loss

### Zero the gradients before running the backward pass.

### Backward pass: 
compute gradient of the loss with respect to all the learnable parameters of the model. Internally, the parameters of each Module are stored in Variables with requires_grad=True, so this call will compute gradients for all learnable parameters in the model.

### Update the weights using gradient descent. 

In [30]:
for t in range(500):
  y_pred = model(x)

  # Compute and print loss.
  loss = loss_fn(y_pred, y)
  print(t, loss.data[0])
  
  # Before the backward pass, use the optimizer object to zero all of the
  # gradients for the variables it will update (which are the learnable weights
  # of the model)
  optimizer.zero_grad()

  # Backward pass: compute gradient of the loss with respect to model parameters
  loss.backward()

  # Calling the step function on an Optimizer makes an update to its parameters
  optimizer.step()

/Users/pymacbit/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  


0 tensor(667.2230)
1 tensor(650.3773)
2 tensor(634.0662)
3 tensor(618.2103)
4 tensor(602.8552)
5 tensor(588.0162)
6 tensor(573.6105)
7 tensor(559.6112)
8 tensor(546.0065)
9 tensor(532.7384)
10 tensor(519.8397)
11 tensor(507.2519)
12 tensor(494.9999)
13 tensor(483.0938)
14 tensor(471.5246)
15 tensor(460.3081)
16 tensor(449.4419)
17 tensor(438.8585)
18 tensor(428.5445)
19 tensor(418.5435)
20 tensor(408.7656)
21 tensor(399.2344)
22 tensor(389.9769)
23 tensor(381.0478)
24 tensor(372.4038)
25 tensor(363.9897)
26 tensor(355.8161)
27 tensor(347.8506)
28 tensor(340.0920)
29 tensor(332.4970)
30 tensor(325.0540)
31 tensor(317.7570)
32 tensor(310.6252)
33 tensor(303.6202)
34 tensor(296.7319)
35 tensor(289.9837)
36 tensor(283.4059)
37 tensor(276.9725)
38 tensor(270.6805)
39 tensor(264.5150)
40 tensor(258.4655)
41 tensor(252.5416)
42 tensor(246.7307)
43 tensor(241.0402)
44 tensor(235.4476)
45 tensor(229.9809)
46 tensor(224.6130)
47 tensor(219.3436)
48 tensor(214.1667)
49 tensor(209.0981)
50 tensor(